add stream format
membraneframework/membrane_remote_stream_format pull request #1
Opened 2020-11-04 16:09 UTC by mat-hek

2020-11-05 12:19 UTC, mickel8 requested changes
We should also change description of repo

2020-11-05 12:19 UTC, mickel8 commented on README.md
> -
What about adding one sentence describing how to use this repo? 

E.g.  You can use this repo for specyfing `caps` in input/output pad e.g. 
```elixir
 def_input_pad :input,
    demand_unit: :buffers,
    caps: [
      {Stream, type: :packet_stream, content: one_of([Opus, nil])}
    ]
```


Or maybe something like in `membrane_opus_format` 
```
Unless you're developing a Membrane Element it's unlikely you need to use this package directly in your app, as normally it is going to be fetched as a dependency of any element that operates on Opus encoded audio.

However, if you are developing an Element or need to add it due to any other reason, the package can be installed by adding membrane_opus_format to your list of dependencies in mix.exs:
```

2020-11-05 12:19 UTC, mickel8 commented on mix.exs
> +defmodule Membrane.Stream.Format.Mixfile do
Cannot add comment to some lines so: we should fix lines 17, 21, 61. There are old `Template` words :slightly_smiling_face:

2020-11-05 12:19 UTC, mickel8 commented on lib/membrane_stream.ex
> +          content: module | nil,
I am wondering if `content` can be missleading here. Someone can think about `content` as some data that is carried in this struct. Maybe change this to `content_format`? On the other hand if someone knows how caps work there shouldn't be any problem with understanding the meaning of this field. What do you think?

2020-11-05 12:42 UTC, mat-hek commented on lib/membrane_stream.ex
> +          content: module | nil,
agreed, content_format seems more intuitive

2020-11-08 21:10 UTC, bblaszkow06 commented on lib/membrane_stream.ex
> +  Generic Membrane data stream format.
TBH, i don't really see the reason for this format to exits. Is there any possible scenario where a format could not be wrapped with Stream? Imagine H264 encoder. Does it produce Stream with content_format H264? Or regular H264? How to make them compatible? Maybe any format should implement behaviour and return `parsed` or `packetized`?
On a second thought, this kind of format might make sense if renamed to `RawStream`, but probably it should be part of core and core should provide some special rules when validating formats to ensure parsed H264 output can be linked to `RawStream(format: H264}` input

2020-11-09 08:58 UTC, mat-hek commented on lib/membrane_stream.ex
> +  Generic Membrane data stream format.
The intention was to have something like 'raw stream', still not sure if it's a good name, as 'raw' relates to 'unencoded', but it's probably better than just 'stream' anyway. The difference between `Stream{format: H264}` and normal H264 is that the former contains unparsed h264, while the latter - parsed H264. Some elements may accept both, while others may accept only one of them.

2020-11-09 09:52 UTC, mat-hek commented on lib/membrane_stream.ex
> +  Generic Membrane data stream format.
maybe `StrangerStream`? :P

2020-11-09 17:03 UTC, mickel8 commented on lib/membrane_stream.ex
> +  Generic Membrane data stream format.
Maybe `IncomingStream` or `RemoteStream`

2020-11-17 07:44 UTC, mickel8 approved these changes

2020-11-17 07:44 UTC, mickel8 commented on README.md
> +[![CircleCI](https://circleci.com/gh/membraneframework/membrane_remote_stream_format.svg?style=svg)](https://circleci.com/gh/membraneframework/membrane_remote_stream_format)
```suggestion
[![Hex.pm](https://img.shields.io/hexpm/v/membrane_remote_stream_format.svg)](https://hex.pm/packages/membrane_remote_stream_format)
[![API Docs](https://img.shields.io/badge/api-docs-yellow.svg?style=flat)](https://hexdocs.pm/membrane_remote_stream_format/)
[![CircleCI](https://circleci.com/gh/membraneframework/membrane_remote_stream_format.svg?style=svg)](https://circleci.com/gh/membraneframework/membrane_remote_stream_format)
```

2020-11-17 09:27 UTC, merged